#!/bin/sh

if [[ -n $(bluetooth | grep 'on') ]]; then
	echo "$(bluetoothctl info | grep Name -m 1 | awk '{print " ", $2}')"

	if [ "$BLOCK_BUTTON" == "1" ]; then
		echo -n "$(~/.scripts/menu_bluetooth)" &> /dev/null
		#alacritty -e bluetoothctl
	fi
fi
