#!/bin/sh
# This is the base file that executes dmenu. Here colors and other options can be configured so they don't need to be changed in every menu file

dmenu -nf '#EEEEEE' -nb '#000000' -sb '#EEEEEE' -sf '#253d3c' -p "$1"\
	-fn 'Noto Sans Mono-10' -h 24 -i -b $(if [[ -n "$2" ]]; then echo "$2"; fi)
#rofi -dmenu -location 5 -width 100 \
#		 -lines 0 -line-margin 0 -line-padding 0 \
#		 -separator-style none -font "Noto Sans Mono 10" -columns 9 -bw 0 \
#		 -disable-history \
#		 -hide-scrollbar \
#		 -color-window "#222222, #222222, #b1b4b3" \
#		 -color-normal "#222222, #b1b4b3, #222222, #005577, #b1b4b3" \
#		 -color-active "#222222, #b1b4b3, #222222, #007763, #b1b4b3" \
#		 -color-urgent "#222222, #b1b4b3, #222222, #77003d, #b1b4b3" \
#		 -kb-row-select "Tab" -kb-row-tab ""
