#!/bin/sh

#trap "exit" INT TERM
#trap "kill 0" EXIT
#echo | ~/.scripts/menu_bone "Place your finger on the fingerprint sensor to execute \"$1\"" "-mask" | sudo -S $1

id=$(($(ls /tmp | grep fprint_request | tail -1 | tail -c +16) + 1))
touch "/tmp/fprint_request_$id"
pkill -RTMIN+11 i3blocks
SUDO_ASKPASS=~/.scripts/menu_passwd sudo -A $1
rm /tmp/fprint_request_$id
pkill -RTMIN+11 i3blocks

