#!/bin/sh

monitor=$(xrandr | grep " connected" | awk '{print $1}' | ~/.scripts/menu_bone -p 'monitor to modify:')
if [[ -n $monitor ]]; then
	chosen=$(echo -e "left of...\nright of...\nabove...\nbelow...\nduplicate\nonly\nprimary\noff" | ~/.scripts/menu_bone -p 'options:')

	case "$chosen" in
		"right of...") 
			monitor2=$(xrandr | grep " connected" | awk '{print $1}' | ~/.scripts/menu_bone -p "$monitor right of:");
			xrandr --output $monitor2 --auto; xrandr --output $monitor --auto --right-of $monitor2;
                        ~/.fehbg;;
		"left of...")
			monitor2=$(xrandr | grep " connected" | awk '{print $1}' | ~/.scripts/menu_bone -p "$monitor left of:");
			xrandr --output $monitor2 --auto; xrandr --output $monitor --auto --left-of $monitor2;
                        ~/.fehbg;;
		"above...")
			monitor2=$(xrandr | grep " connected" | awk '{print $1}' | ~/.scripts/menu_bone -p "$monitor above:");
			xrandr --output $monitor2 --auto; xrandr --output $monitor --auto --above $monitor2;
                        ~/.fehbg;;
		"below...")
			monitor2=$(xrandr | grep " connected" | awk '{print $1}' | ~/.scripts/menu_bone -p "$monitor below:");
			xrandr --output $monitor2 --auto; xrandr --output $monitor --auto --below $monitor2;
                        ~/.fehbg;;
		duplicate)
			monitor2=$(xrandr | grep " connected" | awk '{print $1}' | ~/.scripts/menu_bone -p "$monitor same as:");
			xrandr --output $monitor --auto; xrandr --output $monitor2 --auto --same-as $monitor;
                        ~/.fehbg;;
		only)
			for mon in $(xrandr --listactivemonitors); do
				xrandr --output $mon --off;
			done
			xrandr --output $monitor --auto;;
		primary)
			xrandr --output $monitor --primary;;

		off) xrandr --output $monitor --off;;
	esac
fi

#monitor1=$(xrandr | grep " connected" | awk 'NR == 1 {print $1}')
#monitor2=$(xrandr | grep " connected" | awk 'NR == 2 {print $1}')
#
#case "$chosen" in
#	"extend right") xrandr --output $monitor1 --auto; xrandr --output $monitor2 --auto --right-of $monitor1 ;;
#	"extend left") xrandr --output $monitor1 --auto; xrandr --output $monitor2 --auto --left-of $monitor1 ;;
#	duplicate) xrandr --output $monitor1 --auto; xrandr --output $monitor2 --auto --same-as $monitor1 ;;
#	"first only") xrandr --output $monitor2 --off; xrandr --output $monitor1 --auto ;;
#	"second only") xrandr --output $monitor1 --off; xrandr --output $monitor2 --auto ;;
#esac
